## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  # - nightly
notifications:
  email: false
git:
  depth: 99999999
env:
  global:
    - PYTHON=conda # necessary for SymPy
  matrix:
   - USE_POWER_DYN_MASTER=true
#  allow_failures:
#      - USE_POWER_DYN_MASTER=false

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#    - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
before_install:
  - julia -e "using InteractiveUtils; versioninfo();"
  - if [ $USE_POWER_DYN_MASTER = true ]; then julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaEnergy/PowerDynBase.jl.git"))'; fi

before_script:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Documenter", version="0.19"))'

# uncomment the following lines to override the default test script
jobs:
  include:
    - stage: "Tests"
      name: "Unit/Integration Tests"
      script:
        - julia --check-bounds=yes --color=yes --inline=no -e "using Pkg; Pkg.test(coverage=true)"
      after_success:
        # push coverage results to Codecov
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - name: "Documentation Test"
      script:
        - julia docs/make.jl
    - name: "Changelog Check"
      if: type IN (pull_request)
      before_install:
      before_script:
      script:
        - git fetch origin master:master
        # show all changed files for debugging
        - git diff HEAD master --name-only
        # check if CHANGELOG.md has been modified
        - git diff HEAD master --name-only | grep ^CHANGELOG.md$
